version: '3.8'
services:
  fastapi-app:
    container_name: ${DOCKERHUB_USERNAME}/backend
    environment:
      - DB_DB=${DB_DB}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
    ports:
      - "8080:8000"
    restart: unless-stopped

  svelte-app:
    container_name: ${DOCKERHUB_USERNAME}/frontend
    depends_on:
      - fastapi-app
    # fastapi-app 서비스가 먼저 실행되어야 합니다.
#          condition: service_completed_successfully  # fastapi-app 서비스가 정상적으로 실행되었을 때만 svelte-app 서비스를 실행합니다.
    ports:
      - "5173:5173"
    restart: unless-stopped